title: "Javier Sanchez Toledano"
email: js.toledano@comunidad.unam.mx
description: >- # this means to ignore newlines until "baseurl:"
 Sitio personal de Javier Sanchez Toledano
 Personal site for Javier Sanchez Toledano
baseurl: "/" 
url: "/" 
twitter_username: jstoledano
github_username:  jstoledano

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg